<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.freightcom.clickship</groupId>
		<artifactId>cs-app</artifactId>
		<version>6.0.0-SNAPSHOT</version>
	</parent>

	<artifactId>cs-client</artifactId>

	<name>cs-client</name>

	<scm>
		<connection>scm:svn:http://104.153.56.169:18080/svn/clickship20/cs-app/trunk/cs-client</connection>
		<developerConnection>scm:svn:http://104.153.56.169:18080/svn/clickship20/cs-app/trunk/cs-client</developerConnection>
		<url>http://104.153.56.169:18080/svn/clickship20/cs-app/trunk/cs-client</url>
	</scm>

	<properties>
		<axis2.version>1.8.2</axis2.version>
		<opensaml.version>4.0.1</opensaml.version>
		<apache.cxf.version>4.0.4</apache.cxf.version>
		<cs.app.version>6.0.0-SNAPSHOT</cs.app.version>
		<puro.api.version>2.0.0-SNAPSHOT</puro.api.version>
		<canpar.api.version>2.0.0-SNAPSHOT</canpar.api.version>
	</properties>

	<dependencies>

		<dependency>
			<groupId>com.freightcom.clickship</groupId>
			<artifactId>cs-model</artifactId>
			<version>${cs.app.version}</version>
			<exclusions>
				<exclusion>
					<groupId>jakarta.xml.bind</groupId>
					<artifactId>jakarta.xml.bind-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>com.freightcom.clickship</groupId>
			<artifactId>canpar-rating-service-ws-client</artifactId>
			<version>${canpar.api.version}</version>
		</dependency>

		<dependency>
			<groupId>com.freightcom.clickship</groupId>
			<artifactId>canpar-addon-service-ws-client</artifactId>
			<version>${canpar.api.version}</version>
		</dependency>
		
		<dependency>
			<groupId>com.freightcom.clickship</groupId>
			<artifactId>canpar-business-service-ws-client</artifactId>
			<version>${canpar.api.version}</version>
		</dependency>
		
		<dependency>
			<groupId>com.freightcom.clickship</groupId>
			<artifactId>purolator-zipvalidator-ws-client</artifactId>
			<version>${puro.api.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.apache.httpcomponents.client5</groupId>
			<artifactId>httpclient5</artifactId>
		</dependency>

		<!-- Added to client -->
		<!-- APACHE CXF - start -->
		<dependency>
			<groupId>org.apache.cxf</groupId>
			<artifactId>cxf-rt-frontend-jaxws</artifactId>
			<version>${apache.cxf.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.glassfish.jaxb</groupId>
					<artifactId>jaxb-runtime</artifactId>
				</exclusion>
				<exclusion>
					<groupId>jakarta.xml.bind</groupId>
					<artifactId>jakarta.xml.bind-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>jakarta.activation</groupId>
					<artifactId>jakarta.activation-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.apache.cxf</groupId>
			<artifactId>cxf-rt-ws-security</artifactId>
			<version>${apache.cxf.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.opensaml</groupId>
					<artifactId>opensaml-saml-impl</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.opensaml</groupId>
					<artifactId>opensaml-xacml-impl</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.opensaml</groupId>
					<artifactId>opensaml-xacml-saml-impl</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.glassfish.jaxb</groupId>
					<artifactId>jaxb-runtime</artifactId>
				</exclusion>
				<exclusion>
					<groupId>jakarta.activation</groupId>
					<artifactId>jakarta.activation-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.apache.cxf</groupId>
			<artifactId>cxf-rt-transports-http</artifactId>
			<version>${apache.cxf.version}</version>
		</dependency>

		<dependency>
			<groupId>org.apache.cxf</groupId>
			<artifactId>cxf-rt-transports-http-jetty</artifactId>
			<version>${apache.cxf.version}</version>
		</dependency>
		
		<dependency>
			<groupId>org.opensaml</groupId>
			<artifactId>opensaml-saml-impl</artifactId>
			<version>${opensaml.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.glassfish.jaxb</groupId>
					<artifactId>jaxb-runtime</artifactId>
				</exclusion>
				<exclusion>
					<groupId>jakarta.xml.bind</groupId>
					<artifactId>jakarta.xml.bind-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		
		<dependency>
			<groupId>org.opensaml</groupId>
			<artifactId>opensaml-xacml-impl</artifactId>
			<version>${opensaml.version}</version>
		</dependency>
		
		<dependency>
			<groupId>org.opensaml</groupId>
			<artifactId>opensaml-xacml-saml-impl</artifactId>
			<version>${opensaml.version}</version>
		</dependency>
		<!-- APACHE CXF - end -->
		
		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
			<version>4.0.1</version>
		</dependency>
		
		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-impl</artifactId>
			<scope>runtime</scope>
			<exclusions>
				<exclusion>
					<groupId>jakarta.xml.bind</groupId>
					<artifactId>jakarta.xml.bind-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<!-- Axis 2 dependencies -->
		<dependency>
			<groupId>org.apache.axis2</groupId>
			<artifactId>axis2-kernel</artifactId>
			<version>${axis2.version}</version>
		</dependency>

		<dependency>
			<groupId>org.apache.axis2</groupId>
			<artifactId>axis2-adb</artifactId>
			<version>${axis2.version}</version>
		</dependency>

		<dependency>
			<groupId>org.apache.axis2</groupId>
			<artifactId>axis2-transport-http</artifactId>
			<version>${axis2.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.httpcomponents</groupId>
					<artifactId>httpclient</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.apache.axis2</groupId>
			<artifactId>axis2-transport-local</artifactId>
			<version>${axis2.version}</version>
		</dependency>

		<!-- ebay api digital signature start -->
		<dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>nimbus-jose-jwt</artifactId>
            <version>9.23</version>
        </dependency>
      
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.70</version>
        </dependency>
        
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk15on</artifactId>
            <version>1.70</version>
        </dependency>
		<!-- ebay api digital signature end -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<exclusions>
				<exclusion>
					<groupId>com.vaadin.external.google</groupId>
					<artifactId>android-json</artifactId>
				</exclusion>
				<exclusion>
					<groupId>jakarta.xml.bind</groupId>
					<artifactId>jakarta.xml.bind-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>jakarta.activation</groupId>
					<artifactId>jakarta.activation-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

	<build>
		<!-- include non-java src files in the same place in the output jar -->
		<resources>
			<resource>
				<directory>src/main/java</directory>
				<includes>
					<include>**/*.index</include>
				</includes>
				<filtering>true</filtering>
			</resource>
		</resources>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>