<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.freightcom.clickship</groupId>
		<artifactId>cs-app</artifactId>
		<version>6.0.0-SNAPSHOT</version>
	</parent>

	<artifactId>cs-model</artifactId>

	<name>cs-model</name>

	<scm>
		<connection>scm:svn:http://104.153.56.169:18080/svn/clickship20/cs-app/trunk/cs-model</connection>
		<developerConnection>scm:svn:http://104.153.56.169:18080/svn/clickship20/cs-app/trunk/cs-model</developerConnection>
		<url>http://104.153.56.169:18080/svn/clickship20/cs-app/trunk/cs-model</url>
	</scm>

	<dependencies>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-web</artifactId>
		</dependency>

		<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
			<version>2.0.1.Final</version>
		</dependency>

		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-secretsmanager</artifactId>
			<version>1.12.676</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.httpcomponents</groupId>
					<artifactId>httpclient</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-s3</artifactId>
			<version>1.12.676</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.httpcomponents</groupId>
					<artifactId>httpclient</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
		</dependency>

		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
		</dependency>

		<dependency>
			<groupId>org.atteo.classindex</groupId>
			<artifactId>classindex</artifactId>
			<version>3.4</version>
		</dependency>
		
		<dependency>
			<groupId>com.mandrillapp.wrapper.lutung</groupId>
			<artifactId>lutung</artifactId>
			<version>0.0.8</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.httpcomponents</groupId>
					<artifactId>httpclient</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		
		<dependency>
			<groupId>com.github.alexanderwe</groupId>
			<artifactId>bananaj</artifactId>
			<version>1.2.5-alpha</version>
			<exclusions>
				<exclusion>
					<groupId>log4j</groupId>
					<artifactId>log4j</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.httpcomponents</groupId>
					<artifactId>httpclient</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

<!--		<dependency>
			<groupId>com.netflix.graphql.dgs</groupId>
			<artifactId>graphql-dgs-client</artifactId>
			<version>9.0.4</version>
		</dependency>
		
		<dependency>
			<groupId>com.netflix.graphql.dgs.codegen</groupId>
			<artifactId>graphql-dgs-codegen-shared-core</artifactId>
			<version>6.2.2</version>
			<scope>runtime</scope>
		</dependency> -->

<!--		<dependency>
			<groupId>com.freightcom.clickship</groupId>
			<artifactId>shopify-graphql-client-netflix</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency> -->	
	</dependencies>

	<build>
		<!-- include non-java src files in the same place in the output jar -->
		<resources>
			<resource>
				<directory>src/main/java</directory>
				<includes>
					<include>**/*.index</include>
				</includes>
				<filtering>true</filtering>
			</resource>
		</resources>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>