package com.freightcom.clickship.client.freightcom.v2;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.freightcom.clickship.model.v2.claim.ClaimDTO;

public class TestFreightcomClientV3 {
		public static void main(String[] args) {
		test();
	}

		public static void test() {
			String json = "{\"shipping_details\": {\r\n"
					+ "                \"id\": \"jayIDFdimroejWDHvRhcfYLPFxt3WFRc\",\r\n"
					+ "                \"expected_ship_date\": {\r\n"
					+ "                    \"year\": 2021,\r\n"
					+ "                    \"month\": 8,\r\n"
					+ "                    \"day\": 10\r\n"
					+ "                },\r\n"
					+ "                \"origin\": {\r\n"
					+ "                    \"name\": \"Mike INc n67676766\",\r\n"
					+ "                    \"address\": {\r\n"
					+ "                        \"address_line1\": \"2120 Baker\",\r\n"
					+ "                        \"address_line2\": \"\",\r\n"
					+ "                        \"unit_number\": \"\",\r\n"
					+ "                        \"city\": \"Burlington\",\r\n"
					+ "                        \"region\": \"ON\",\r\n"
					+ "                        \"country\": \"CA\",\r\n"
					+ "                        \"postal_code\": \"L7L 0A8\",\r\n"
					+ "                        \"validated\": false\r\n"
					+ "                    },\r\n"
					+ "                    \"residential\": false,\r\n"
					+ "                    \"business_type\": \"commercial-business\",\r\n"
					+ "                    \"tailgate_required\": false,\r\n"
					+ "                    \"instructions\": \"Leave at back\",\r\n"
					+ "                    \"contact_name\": \"Bob\",\r\n"
					+ "                    \"phone_number\": {\r\n"
					+ "                        \"number\": \"4444444444\",\r\n"
					+ "                        \"extension\": \"\"\r\n"
					+ "                    },\r\n"
					+ "                    \"email_addresses\": [\r\n"
					+ "                        \"mrochon@freightcom.com\"\r\n"
					+ "                    ],\r\n"
					+ "                    \"receives_email_updates\": true,\r\n"
					+ "                    \"address_book_contact_id\": \"\"\r\n"
					+ "                },\r\n"
					+ "                \"destination\": {\r\n"
					+ "                    \"name\": \"Miker Inccccc\",\r\n"
					+ "                    \"address\": {\r\n"
					+ "                        \"address_line1\": \"2121 Baker Drive\",\r\n"
					+ "                        \"address_line2\": \"\",\r\n"
					+ "                        \"unit_number\": \"\",\r\n"
					+ "                        \"city\": \"Burlington\",\r\n"
					+ "                        \"region\": \"ON\",\r\n"
					+ "                        \"country\": \"CA\",\r\n"
					+ "                        \"postal_code\": \"L7L 0A8\",\r\n"
					+ "                        \"validated\": false\r\n"
					+ "                    },\r\n"
					+ "                    \"residential\": false,\r\n"
					+ "                    \"business_type\": \"commercial-business\",\r\n"
					+ "                    \"tailgate_required\": false,\r\n"
					+ "                    \"instructions\": \"\",\r\n"
					+ "                    \"contact_name\": \"fff\",\r\n"
					+ "                    \"phone_number\": {\r\n"
					+ "                        \"number\": \"44444444444\",\r\n"
					+ "                        \"extension\": \"\"\r\n"
					+ "                    },\r\n"
					+ "                    \"email_addresses\": [\r\n"
					+ "                        \"mrochon@freightcom.com\"\r\n"
					+ "                    ],\r\n"
					+ "                    \"receives_email_updates\": false,\r\n"
					+ "                    \"address_book_contact_id\": \"\",\r\n"
					+ "                    \"ready_at\": {\r\n"
					+ "                        \"hour\": 9,\r\n"
					+ "                        \"minute\": 0,\r\n"
					+ "                        \"populated\": true\r\n"
					+ "                    },\r\n"
					+ "                    \"ready_until\": {\r\n"
					+ "                        \"hour\": 17,\r\n"
					+ "                        \"minute\": 0,\r\n"
					+ "                        \"populated\": true\r\n"
					+ "                    },\r\n"
					+ "                    \"signature_requirement\": \"not-required\"\r\n"
					+ "                },\r\n"
					+ "                \"alternate_destination\": {\r\n"
					+ "                    \"name\": \"\",\r\n"
					+ "                    \"address\": {\r\n"
					+ "                        \"address_line1\": \"\",\r\n"
					+ "                        \"address_line2\": \"\",\r\n"
					+ "                        \"unit_number\": \"\",\r\n"
					+ "                        \"city\": \"\",\r\n"
					+ "                        \"region\": \"\",\r\n"
					+ "                        \"country\": \"\",\r\n"
					+ "                        \"postal_code\": \"\",\r\n"
					+ "                        \"validated\": false\r\n"
					+ "                    }\r\n"
					+ "                },\r\n"
					+ "                \"reference_codes\": [\r\n"
					+ "                    \"\"\r\n"
					+ "                ],\r\n"
					+ "                \"packaging_type\": \"pallet\",\r\n"
					+ "                \"packaging_properties\": {\r\n"
					+ "                    \"pallet_type\": \"ltl\",\r\n"
					+ "                    \"pallets\": [\r\n"
					+ "                        {\r\n"
					+ "                            \"measurements\": {\r\n"
					+ "                                \"cuboid\": {\r\n"
					+ "                                    \"l\": 44,\r\n"
					+ "                                    \"w\": 44,\r\n"
					+ "                                    \"h\": 44,\r\n"
					+ "                                    \"unit\": \"in\"\r\n"
					+ "                                },\r\n"
					+ "                                \"weight\": {\r\n"
					+ "                                    \"value\": 555,\r\n"
					+ "                                    \"unit\": \"lb\"\r\n"
					+ "                                }\r\n"
					+ "                            },\r\n"
					+ "                            \"description\": \"fdredt\",\r\n"
					+ "                            \"freight_class\": \"92.5\",\r\n"
					+ "                            \"nmfc\": \"\",\r\n"
					+ "                            \"contents_type\": \"pallet\",\r\n"
					+ "                            \"num_pieces\": 0,\r\n"
					+ "                            \"num_pallets\": 0\r\n"
					+ "                        }\r\n"
					+ "                    ],\r\n"
					+ "                    \"has_stackable_pallets\": false,\r\n"
					+ "                    \"dangerous_goods\": \"\",\r\n"
					+ "                    \"pallet_service_details\": {\r\n"
					+ "                        \"limited_access_delivery_type\": \"\",\r\n"
					+ "                        \"limited_access_delivery_other_name\": \"\",\r\n"
					+ "                        \"in_bond\": false,\r\n"
					+ "                        \"in_bond_details\": null,\r\n"
					+ "                        \"appointment_delivery\": false,\r\n"
					+ "                        \"protect_from_freeze\": false,\r\n"
					+ "                        \"threshold_pickup\": false,\r\n"
					+ "                        \"threshold_delivery\": false,\r\n"
					+ "                        \"trade_show_delivery\": false,\r\n"
					+ "                        \"amazon_or_fbadelivery\": false\r\n"
					+ "                    }\r\n"
					+ "                },\r\n"
					+ "                \"insurance\": {\r\n"
					+ "                    \"type\": \"internal\",\r\n"
					+ "                    \"total_cost\": {\r\n"
					+ "                        \"value\": \"55000\",\r\n"
					+ "                        \"currency\": \"CAD\"\r\n"
					+ "                    },\r\n"
					+ "                    \"terms_accepted\": true,\r\n"
					+ "                    \"terms_accepted_by\": {\r\n"
					+ "                        \"id\": \"jRnsvbj6kq1O07gohvZYSoaRPi7ROvVt\",\r\n"
					+ "                        \"type\": \"user\"\r\n"
					+ "                    }\r\n"
					+ "                }\r\n"
					+ "            }}";
			
			ObjectMapper objectMapper = new ObjectMapper()
				      .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
			
			try {
				ClaimDTO dto = objectMapper.readValue(json, ClaimDTO.class);
				System.out.println(dto);

			} catch (Exception e) {
				System.out.println(e.getLocalizedMessage());
			}
		}
}
