//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.03 at 02:57:10 PM EST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:ebay:apis:eBLBaseComponents", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
@IndexSubclasses
package com.freightcom.clickship.model.marketplace.ebay.user;

import org.atteo.classindex.IndexSubclasses;
